<nav class="navbar navbar-expand-lg navbar-light bg-light">
            <?php
            if (Auth::get('fl_rol') == 1) {
            ?>
            <a class="navbar-brand" href="/kumbia/dashboard/dashboard">DASHBOARD</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto nav-tabs ">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Administrador
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="/kumbia/usuario/listarUsuario">Usuarios</a>
                            <a class="dropdown-item" href="/kumbia/dispositivo/listarDispositivo">Dispositivos</a>
                            <a class="dropdown-item" href="/kumbia/ubicacion/listarUbicacion">Ubicación</a>
                            <a class="dropdown-item" href="#">Area</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Registro de alertas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Registro de notificaciones</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/kumbia/index/salir">Cerrar sesión</a>
                    </li>
                </ul>
            </div>
                <?php } ?>
            <?php
            if (Auth::get('fl_rol') == 2) {
            ?>
            <a class="navbar-brand" href="#">DASHBOARD</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto nav-tabs ">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Registro de alertas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Registro de notificaciones</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/kumbia/default/public/index/salir">Cerrar sesión</a>
                    </li>
                </ul>
            </div>
                <?php } ?>
        </nav>


<?php echo Tag::js('jquery/jquery-3.3.1.slim.min'); ?>
<?php echo Tag::js('jquery/bootstrap'); ?>
